services:
  - type: web
    name: evend-import
    env: python
    pythonVersion: "3.11"        # obligatoire pour compatibilité numpy/pandas
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
