services:
  - type: web
    name: evend-import
    env: python
    plan: free
    region: oregon

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0

    buildCommand: "pip install -r requirements.txt -c constraints.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:10000"

    build:
      apt:
        packages:
          - google-chrome-stable
          - chromium-chromedriver
